### PR TITLE
Update Android SDK Public Sample App

### PR DESCRIPTION
**Pull request by kosyakow**

### CODE REVIEW

**Comment by ravimandala** [comment]
Do we have 2 sample apps in this repo? One in root directory and one in sample/ directory?

Can you create a PR to merge into master instead of 3.3.5 branch?

**Comment by ravimandala** [comment]
@kosyakow: Who is reviewing and approving the changes on this branch now? Sergey? Please assign accordingly and get this merged today as SDK v3.3.5 is already live on the dashboard. Thanks.

**Comment by sergeyksv** [comment]
@pianistic @ravimandala Master was already adjusted for 4.0. This pull request will "downgrade" master to 3.3.5.

**Comment by ravimandala** [comment]
@sergeyksv I think master should not have been adjusted for 4.0
Some publishers who aren't beta testers have gotten their hands on our 4.0.0 build from the sample app. Some issues are being reported by random publishers. Please confirm with Chris and downgrade it to 3.3.5 (our latest public release on the dashboard) and probably have the 4.0 on some other branch.

**Comment by sergeyksv** [comment]
@ravimandala Per @pianistic approval downgraded master branch to 3.3.5. Master forked as 4.0.x-preview branch

**Pull request merged**
